### ISSUE TITLE
org.springframework.messaging.converter.MessageConversionException for /lastUsedRegex

### ISSUE THREAD

**Issue by curchi** [mulithemuli/raas#1]
Hi,

```
org.springframework.messaging.converter.MessageConversionException: Unable to convert payload with type='at.muli.raas.RaasApplication$RegexStats', contentType='null', converter=[CompositeMessageConverter[converters=[org.springframework.messaging.converter.StringMessageConverter@60a19aeb, org.springframework.messaging.converter.ByteArrayMessageConverter@439d4b7e, org.springframework.messaging.converter.MappingJackson2MessageConverter@6b05d705]]]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.doConvert(AbstractMessageSendingTemplate.java:186) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:149) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:128) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:121) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at at.muli.raas.RaasApplication.updateLastUsedRegex(RaasApplication.java:50) ~[classes/:na]
	...
```

The exception was thrown when /lastUsedRegex was requested.
Response:

```
{
"timestamp":"2018-07-08T19:00:47.476+0000",
"status":500,
"error":"Internal Server Error",
"message":"Unable to convert payload with type='at.muli.raas.RaasApplication$RegexStats', contentType='null', converter=[CompositeMessageConverter[converters=[org.springframework.messaging.converter.StringMessageConverter@151845c5, org.springframework.messaging.converter.ByteArrayMessageConverter@32d4e9ba, org.springframework.messaging.converter.MappingJackson2MessageConverter@5d2c3c94]]]",
"path":"/lastUsedRegex"
}
```

After adding getters for the fields at.muli.raas.RaasApplication.RegexStats#{regex, used, lastUsed} no exception was thrown.
Response:
```
{
"regex":"([a-zA-Z0-9_@:!]){4}([a-zA-Z]){2}([0-9]){2}",
"used":1,
"lastUsed":"2018-07-08T20:55:06.087+02:00"
}
```

The following Java version is used:

```
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

OS:
`Fedora release 27 (Twenty Seven)`

Is there something wrong with my setup?

**Comment by mulithemuli** [comment]
The getters schould be created by Lombok.
Wasn't that the case?

**Comment by mulithemuli** [comment]
Two more things to verify:
1. does it work when packaged with mvn clean package and then started with java -jar?
2. Is Lombok installed in Eclipse? https://projectlombok.org/setup/eclipse

**Comment by curchi** [comment]
Hi mulithemuli,

Thanks for your help!

ad 1.)
Yes, it does.

ad 2.)
After installing Lombok in Eclipse everything works as expected.
